---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  image: ghcr.io/advplyr/audiobookshelf
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: audiobookshelf
  filterTags:
    pattern: '^([0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$1'
  policy:
    semver:
      range: '>=0.0.0'
