---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  image: cloudflare/cloudflared
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cloudflared
  filterTags:
    pattern: '^([0-9]{4}\.[0-9]+\.[0-9]+)$'
    extract: '$1'
  policy:
    alphabetical:
      order: desc
